### ISSUE TITLE
E863のエラーメッセージについて

### ISSUE THREAD

**Issue by machakann** [vim-jp/lang-ja#161]
E863のエラーメッセージの原文、訳文は以下のようになっています。

https://github.com/vim-jp/lang-ja/blob/92a2f759b4546809d7c831eff772df63e06ecfe1/src/po/ja.po#L6698-L6699

このエラーは例えば端末の表示されたポップアップウィンドウを閉じずに出ようとしたときにでます。なので、ニュアンスとしては例えば以下の文のほうが近いかと思ったのですがいかがでしょうか。

- ポップアップ端末ウィンドウでは許されません
- ポップアップウィンドウ内端末では許されません

**Comment by h-east** [comment]
Google翻訳結果と指摘内容を加味すると、2番目の案に「の」を加えた
「ポップアップウィンドウ内の端末では許されません」
かなぁ。

**Comment by machakann** [comment]
良いと思います。

**Comment by h-east** [comment]
Thanks
