### ISSUE TITLE
vim-dev に最新版を提出

### ISSUE THREAD

**Issue by koron** [vim-jp/lang-ja#17]
最低限必要な仕事

* euc-jp 版、sjis版を更新する

できたらやりたい

* 上記を自動化

**Comment by koron** [comment]
target date: end of Jan 2016

**Comment by koron** [comment]
現在作業中～

**Comment by koron** [comment]
WIP ですが #33 にPR作成。

**Comment by koron** [comment]
ちょっと、欲がでてきました。

> こうなると自動生成な sjis, euc-jp版はリポジトリから消したり、
> メニューファイルの更新チェックもしたいところ。

**Comment by koron** [comment]
簡単なチェックで、メニューに更新がなさそうなことを確認。

**Comment by koron** [comment]
#33 はマージしました。いまから提出のための作業にはいります。

**Comment by tyru** [comment]
:+1:

**Comment by koron** [comment]
タグ打ちました。 https://github.com/vim-jp/lang-ja/releases/tag/20160131

今からメール送ります。

**Comment by koron** [comment]
DONE!!!
https://groups.google.com/d/msg/vim_dev/IqvO_OTgrs0/67xxQZ_SCgAJ

**Comment by k-takata** [comment]
:+1:

**Comment by crazymaster** [comment]
:+1: 

ところで`released`ブランチ残ってますがこれは？

**Comment by tyru** [comment]
:+1: 

![ありがてえ](http://rr.img.naver.jp/mig?src=http%3A%2F%2Fimgcc.naver.jp%2Fkaze%2Fmission%2FUSER%2F20151108%2F26%2F2310996%2F3%2F313x470xf70e4b8b8e84bfa90a4b0adc.jpg%2F300%2F600&twidth=300&theight=0&qlt=80&res_format=jpg&op=r)

**Comment by crazymaster** [comment]
> ところでreleasedブランチ残ってますがこれは？

要らなさそうなので削除しときます。

**Comment by koron** [comment]
@crazymaster Thanks!
