### ISSUE TITLE
Ubuntu側での変更を取り込む

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/lang-ja#19]
要レビュー＆場合によってはUbuntu側での変更が必要

https://translations.launchpad.net/ubuntu/+source/vim

**Comment by koron** [comment]
Export してみてheaderを見た限り、ココにあった少し古いバージョンのように見えます。

[src_po_vim-ja.zip](https://github.com/vim-jp/lang-ja/files/104118/src_po_vim-ja.zip)

**Comment by koron** [comment]
いずれにせよ、要チェックかな

**Comment by crazymaster** [comment]
システム上、仕方のない事ですが古いバージョンを元にしていますね。

ちなみにpoファイルのダウンロードのところで、"Only strings that differ from imported versions" にチェックを
入れると差分のみが入手できます。あるいは以下のURLで差分が見られます。
https://translations.launchpad.net/ubuntu/xenial/+source/vim/+pots/vim/ja/+translate?show=changed_in_ubuntu

**Comment by koron** [comment]
しかもかなり古い感じですね。

**Comment by crazymaster** [comment]
古いと言っても本家Vimのリポジトリに入っているものですが...

**Comment by koron** [comment]
そうでないのも混ざってます。

**Comment by koron** [comment]
そうでないものの例: https://translations.launchpad.net/ubuntu/xenial/+source/vim/+pots/vim/ja/+translate?batch=10&show=all&search=E127

古いのに、本家の更新にすら追従してないものの例: https://translations.launchpad.net/ubuntu/xenial/+source/vim/+pots/vim/ja/+translate?batch=10&show=all&search=W14

**Comment by crazymaster** [comment]
>そうでないのも混ざってます。

Ubuntu側での変更ですね

**Comment by koron** [comment]
cce4790 で、一部取り込みました。ここで取り込まなかったものは、意図的に落としてます。

主な変更内容は空白の変更。ただ全部というわけではなく、必要なところは残しています。

**Comment by koron** [comment]
> Ubuntu側での変更ですね

E127に限れば、Ubuntu側での変更というよりは、履歴を信じるならばもとから自分たちの訳を採用した感じですね。

**Comment by koron** [comment]
で、本件は終了とします。

**Comment by crazymaster** [comment]
>古いのに、本家の更新にすら追従してないものの例: https://translations.launchpad.net/ubuntu/xenial/+source/vim/+pots/vim/ja/+translate?batch=10&show=all&search=W14

これはレビューがupstreamより後に行われているせいだと思います。
私はUbuntu Translatorsで権限を持っているので、直しておきましょうか？

**Comment by koron** [comment]
お願いします。

ubuntuがリリースしている版との差異もあるので、そこだけ留意してください。

**Comment by crazymaster** [comment]
"既に", "過ぎ" については直しました。
残りは本家側に合わせればいいですか？

**Comment by koron** [comment]
はい。基本全部、ubuntuの翻訳ポリシーに反しないかぎりは、本家側に倒してください。

**Comment by crazymaster** [comment]
本家側に倒したので、これでvim-devに提出後importされれば差分はなくなるはずです。
