### ISSUE TITLE
日本語manファイルをvimdoc-jaから移管

### ISSUE THREAD

**Issue by k-takata** [vim-jp/lang-ja#22]
https://github.com/vim-jp/vimdoc-ja には、以下の日本語manファイルが含まれていますが、本家に取り込まれているファイルを一括管理するという意味で lang-ja に移管したほうがよいと思います。

* evim-ja.UTF-8.1
* vim-ja.UTF-8.1
* vimdiff-ja.UTF-8.1
* vimtutor-ja.UTF-8.1
* xxd-ja.UTF-8.1

どうでしょうか。

**Comment by koron** [comment]
私は基本賛成です。が、いくつかクリアにしたい事項があります。

1. vimdoc-ja での同意
2. 当面の更新窓口が私になってしまうのは可か?

とりあえず、以上。

**Comment by k-takata** [comment]
> 当面の更新窓口が私になってしまうのは可か?

私は問題ないと思います。

そういえば、vimdoc-ja では、翻訳元の英語版を en ディレクトリに置いていましたが、それをどう運用するか考えないといけないですね。

**Comment by mattn** [comment]
問題なし

**Comment by koron** [comment]
done by #25
