### ISSUE TITLE
Makeの訳について

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/lang-ja#26]
https://github.com/vim-jp/lang-ja/blob/master/runtime/lang/menu_ja_jp.utf-8.vim#L142

"Make" のローカライズが "メイク" になっているのに違和感を覚えるのは自分だけでしょうか？
何か根拠になるものがあればいいのですが...

**Comment by mattn** [comment]
Make の良い日本語訳って無いですね。

**Comment by koron** [comment]
原文で `Make` と残すのも、それはそれでおさまりが悪いんですよね。

もしくは `ビルド` にしてしまうのは、ありかもしれません。

**Comment by koron** [comment]
もういっそ `ﾑｰﾝ･ﾌﾟﾘｽﾞﾑﾊﾟﾜｰ･ﾒｲｸｱｯﾌﾟ!` とかにしちゃおうかな…

**Comment by koron** [comment]
特に良いアイデアがないのであれば `ビルド` に変更しようと考えてます。

理由なのですが、 `Make` のまま残すのはいままでの翻訳の経験から論外かなと。
(どんな形であれアルファベットが残ってることは許されない風調)
話し言葉的には `メイク` or `メーク` ですが、これに多少なりとも違和感があることは事実です。
対して `ビルド` はかなり意訳になってしまいますが、
IDE でも同様の機能を起動するメニュー項目は `ビルド` となっているので、
それなりに馴染みがあると現時点では判断しました。

**Comment by koron** [comment]
@crazymaster どうでしょう?

**Comment by crazymaster** [comment]
私も特にいいアイデアはないですし、横のほうに ":make" が表示されるので
"ビルド" で良いかなと思います。

**Comment by koron** [comment]
@crazymaster thx! では `ビルド` にしてみましょう。

**Comment by koron** [comment]
will be fixed in #31
