### ISSUE TITLE
Switching to backtracking RE engine for patternの訳

### ISSUE THREAD

**Issue by k-takata** [vim-jp/lang-ja#29]
https://github.com/vim-jp/lang-ja/pull/16/files#r50748664 から起票。

"Switching to backtracking RE engine for pattern:" の訳が "次のパターンのためにバックトラッキング正規表現エンジンに切り替えます: " となっていますが、「のために」の部分が若干不自然に感じます。
意味的には正確さに欠けますが、「を」にするか、

> この分、verbose 時に出る用ので「～のために」は強調しない方がよい気がします。いっそパターンという表記を抜くくらいの感じが自然っぽい。

という意見が出ていますが、何かいい訳ありますか？

**Comment by h-east** [comment]
`"次のパターン用にバックトラッキング正規表現エンジンに切り替えます: "`
とかどうでしょうか？

**Comment by koron** [comment]
次のパターンにバックトラッキング RE エンジンを適用します: %s

こんなんでどうでしょ。 `swtiching` を残そうとしなければ、読める日本語にはできます。
あと指摘外ですが、verbose時ということで `RE` は翻訳しなくても良いかな、という気になってきました。

**Comment by mattn** [comment]
@koron いいね

**Comment by koron** [comment]
@mattn thx!

あとは RE として残すことについて専門家 @k-takata の意見が聞きたいです。

**Comment by k-takata** [comment]
いい感じですね。
REは悩ましいなあ。まー、どっちでも。

**Comment by koron** [comment]
とりあえず RE 残します。

**Comment by koron** [comment]
PR #31 で修正予定です。
