### ISSUE TITLE
*.mo を作る

### ISSUE THREAD

**Issue by koron** [vim-jp/lang-ja#38]
リリース時のテストの一部として .mo を生成してみる必要がある。

関連 #20

**Comment by koron** [comment]
msgfmt が 0.19.6 だと ja.sjis.po に対して上手くかからない。 `\\表` みたいなのがあるとダメ。

**Comment by k-takata** [comment]
それ、私もこの前はまりました。環境変数の設定が必要です。

**Comment by koron** [comment]
`OLD_PO_FILE_INPUT` ?

**Comment by k-takata** [comment]
それです。

**Comment by koron** [comment]
さっき試したら、機能しなかったんですよね…

**Comment by koron** [comment]
あ、したw

あれ?

**Comment by k-takata** [comment]
gettextとmake（とshell）は何を使っています？
MSYS2 or Cygwin?
MSYS2のmakeを使ったりすると、bashから実行した場合と、cmd.exeから実行した場合とで、動作が変わったりしてはまりました。

**Comment by koron** [comment]
msys2だと、起動するシェルによるロケール周りの自動設定とか、なにかありそうですね…

**Comment by koron** [comment]
done in #42

**Comment by k-takata** [comment]
ちなみに、v7.4.992 で src/po/ のメイクファイルを更新しましたが、 実は Make_ming.mak は、bash から動かすとちゃんと動きませんｗ
一応、bash / cmd.exeのどちらからでも動くようにしたパッチは用意していますが、投げてません。

**Comment by koron** [comment]
やっぱそろそろ ja.sjis.po と ja.euc-jp.po は廃止すべき時期に来てるんじゃないですかね?
GNU gettextはiconv対応しているのでUTF-8版があれば十分。
非GNUなgettext環境は、UTF-8必須になっちゃいますけど、HPとかだけでいまやレアなので
日本語版としては切り捨てて良いのかなと。

**Comment by k-takata** [comment]
次の正式インストーラは、今まで通りBramが作るのか、それとも vim-win32-installer からそのまま持ってくるのかどっちになるんでしょうね。ちゃんとiconv対応版が同梱されればそれで問題ないのでしょうが。

**Comment by koron** [comment]
もう vim-win32-installer でええんちゃうかな…
master and develop 制に移行してくれるのがベストだけど

**Comment by tyru** [comment]
あれ、vim-win32-installerって本家にマージされたんじゃなかったでしたっけ？

**Comment by koron** [comment]
vim/vim-win32-installer ができた。

**Comment by tyru** [comment]
なるほど、マージされたけどまだ実際のインストーラ自体は作られてない感じですね。

**Comment by k-takata** [comment]
vim organization以下に移動は完了して、1日1回のビルドも走るようになりました。あとは何人かがちゃんと動いたよと報告してくれれば、vim.org のダウンロードページからリンクが張られて、晴れて正式のナイトリービルドという扱いになるはずです。
あとは、適当なタイミングで、Bram自身がじっくりテストして問題ないと判断されたものは、vim.org の ftp サーバーにコピーされて、安定版という扱いになるようです。
ただ、7.5 の正式版も vim-win32-installer のビルドが使われるのかはわかりません。

**Comment by tyru** [comment]
なるほど。詳細な情報ありがとうございます。
これに関してとある方面に間違った説明をしてしまったようなので、誤りを訂正します…

**Comment by k-takata** [comment]
ちなみに、今朝の最新インストーラ
https://github.com/vim/vim-win32-installer/releases/tag/v7.4.1236

**Comment by k-takata** [comment]
Bram自身の発言は、以下の通り
https://groups.google.com/d/msg/vim_dev/dAXpcpHmVw4/YkpJUJ0mCAAJ

> That looks nice!  Redirecting from the Vim doesnload page to here would
> make most people happy.  I think the only hint that's needed is "in case
> you don't have a preference, download the "_x86.exe" file and run it".
> 
> Once in a while I can take one of the builds and put it on ftp.vim.org
> and link to it directly from the download page.  This would be the
> "stable version".  It will never be the latest, since it takes a few
> days to make sure that there are no regressions.
