### ISSUE TITLE
最新版 (7.4.507) への追従

### ISSUE THREAD

**Issue by k-takata** [vim-jp/lang-ja#6]
7.4.296 の直前のコミットで *.po が変更されているので、そのマージも必要。

**Comment by koron** [comment]
#16 で対応します。

**Comment by k-takata** [comment]
smackの細切れメッセージの件、投げました。
https://groups.google.com/d/topic/vim_dev/1LMoZN6oD1w/discussion

**Comment by k-takata** [comment]
7.4.1186
https://groups.google.com/d/topic/vim_dev/XwSrbV7QoAw/discussion

**Comment by k-takata** [comment]
修正方法については、

> Thanks.  yes, the file name may contain special characters and those
> need to be translated.  But then the newline also gets translated, thus
> it has to be written separately:

とのことでした。
