### ISSUE TITLE
表記のゆらぎ 「超」「越」

### ISSUE THREAD

**Issue by nakinor** [vim-jp/lang-ja#68]
どちらを使うのが適切なのかわかりませんが、同じ "Cannot go beyond last ..." でも異なっているのが気になりました(同じにする必要もないかもしれませんが)。

「超え」
```
msgid "E198: cmd_pchar beyond the command length"
msgstr "E198: cmd_pchar がコマンド長を超えました"

msgid "E322: line number out of range: %ld past the end"
msgstr "E322: 行番号が範囲外です: %ld 超えています"

msgid "E425: Cannot go before first matching tag"
msgstr "E425: 最初の該当タグを超えて戻ることはできません"

msgid "E428: Cannot go beyond last matching tag"
msgstr "E428: 最後に該当するタグを超えて進むことはできません"

msgid "E132: Function call depth is higher than 'maxfuncdepth'"
msgstr "E132: 関数呼出の入れ子数が 'maxfuncdepth' を超えました"
```

「越え」

```
msgid "E87: Cannot go beyond last buffer"
msgstr "E87: 最後のバッファを越えて移動はできません"

msgid "E727: Start past end"
msgstr "E727: 開始位置が終了位置を越えました"

msgid "E165: Cannot go beyond last file"
msgstr "E165: 最後のファイルを越えて後には行けません"
```

**Comment by koron** [comment]
国語的には調べた限りどっちを使っても良さそうです。
ただどちらかといえば「超」に統一ですかねぇ?

**Comment by k-takata** [comment]
基本的にはどちらでもよさそうな気がしますが、数値が超過する場合にはどちらかというと「超」がふさわしい気がします。
一方、位置的なものには「越」がふさわしい気がします。例えば、「飛び越える」「山越え」などには「超」は使いません。
そう考えると、E425, E428は「越」の方がふさわしいかもしれません。残りはそのままがよさそう？

**Comment by nakinor** [comment]
無理に合わせる必要はありませんよね……
k-takata さんの方針が良さそうですね。

**Comment by koron** [comment]
参考までに http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1044734835 より

> 「越える」の方は、山を越える、峠を越える、国境を越えるのように、移動して通り過ぎる、向こうに行く場合に限られます。
> 
> 「超える」の方は、基準や限界、数量、金額などが上回る場合に用います。
