### ISSUE TITLE
句読点は統一するべきか

### ISSUE THREAD

**Issue by mattn** [vim-jp/lang-ja#75]
ja.po に関して
```
E319: このバージョンではこのコマンドは利用できません, ごめんなさい
```
* 最後が「。」で終わる物、終わらない物
* 句読点に「、」が使われている物、「, 」(半角カンマとスペース1個)が使われている物

個人的には一般ユーザ向けの文章なので「, 」は無いかなと思ったのでしょうがどうでしょうか。

「、」の使用は11個、「, 」の使用は38個

**Comment by koron** [comment]
たぶん最初は `, ` 使っていたんじゃないかな。

`、` への統一で良いんじゃないでしょうか。

**Comment by k-takata** [comment]
#81 で、列挙に使っている部分を除いてだいたい統一できたと思いますので閉じます。
